targets:
  $default:
    builders:
      json_serializable:
        options:
          #field_rename: snake
          explicit_to_json: true
      freezed:
        options:
          union_key: type
          union_value_case: snake
